version: '3.7'
services:
    db:
        image: postgres:9
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"
