version: '3.7'
services:
    db:
        image: postgres:9
        restart: always
        environment:
            - "POSTGRES_USER=postgres"
            - "POSTGRES_PASSWORD=postgres"
        volumes:
            - pgsql-data:/var/lib/postgresql/data
            - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"

    gradle:
        image: gradle:5.0-jdk11
        volumes: 
            - ./spring:/gradle
        working_dir: /gradle
        environment:
            - "JDBC_DATABASE_URL=jdbc:postgresql://db:5432/outgo"
            - "JDBC_DATABASE_USERNAME=postgres"
            - "JDBC_DATABASE_PASSWORD=postgres"
            - SLACK_TOKEN
            - SLACK_BOT_ACCESS
        ports:
            - "8080:8080"
        entrypoint:
            - gradle
        command: bootRun

    npm:
        image: "node:12.10"
        ports:
            - "8081:8081"
        volumes:
            - .:/src/web
        working_dir: "/src/web/vue"
        entrypoint:
            - npm
        command: run dev

volumes:
    pgsql-data:
