runtime: java
env: flex

runtime_config:
   jdk: openjdk8

handlers:
- url: /
  mime_type: text/html
  static_files: public/index.html
  upload: public/index.html

- url: /dist
  static_dir: public/dist

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
